import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../../../components/Navbar';
import { NavbarBetter } from '../../../components/NavbarBetter';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Australia is the new Canada?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.svg" />
            </Head>
            <NavbarBetter />
            <main className='p-20'>
                <h1 className='text-9xl text-slate-800'>AUSTRALIA IS THE NEW CANADA?</h1>
                <div className=" flex  justify-end">
                    <div className=" w-2/5 mx-32">
                        <p className='text-left'>
                            The election results raise very interesting questions about the
                            future of Australian politics and in particular, the Australian
                            electoral system. The Labor party secured a majority with historically
                            low 32.8% primary vote. However, they were preferenced to govern
                            by 52% of voters when all is said an done. In Canada, Trudeaus Liberals
                            have one two elections in a row by being to the left of the Conservative
                            but to the right of the New Democrats - is Australia heading to a system
                            where Labor is the natural party of government off the back of Greens
                            preferences?
                        </p>
                    </div>

                </div>


            </main>

            <footer>
                Just another footer
            </footer>
        </div>
    )
}
