import Head from 'next/head';
export default function Home() {
    return (
        <div>
            <Head>
                <title>Australia is the new Canada?</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/icon.svg" />
            </Head>
            <div className="snap-y snap-proximity overflow-y-scroll h-screen">
                <section className="bg-politicalRed h-screen flex items-center justify-center snap-start"><h1 className=' font-bold'>First Page</h1></section>
                <section className="bg-politicalYellow h-screen flex items-center justify-center snap-start"><h1 className=' font-bold'>Second Page</h1></section>
                <section className="bg-politicalTeal h-screen flex items-center justify-center snap-start"><h1 className=' font-bold'>Third Page</h1></section>
                <section className="bg-politicalOrange h-screen flex items-center justify-center snap-start"><h1 className=' font-bold'>Fourth Page</h1></section>
            </div>

        </div>
    )
}
