import Head from 'next/head'
import Image from 'next/image'
import { Navbar } from '../components/Navbar';
import { Hero } from '../components/Hero';
import { Issues } from '../components/Issues';
import { Authors } from '../components/Authors';
import { Footer } from '../components/Footer';
import { CallToAction } from '../components/CallToAction';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar />

      <Hero latestIssue="first-issue"/>

      <Issues />
      
      <Authors />

      <CallToAction />

      <Footer />

    </div>
  )
}
