import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Navbar } from '../../components/homepage/Navbar';
import { Hero } from '../../components/homepage/Hero';
import { Issues } from '../../components/homepage/Issues';
import { Authors } from '../../components/homepage/Authors';
import { Footer } from '../../components/homepage/Footer';
import { CallToAction } from '../../components/homepage/CallToAction';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <Hero />

      <Issues />
      
      <Authors />

      <CallToAction />

      <Footer />

    </div>
  )
}
